name: Test PR

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # this is required for the subsequent build to be able to push to the registry on localhost:5000
          driver-opts: network=host

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: localhost:5000/kroxy-jekyll:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
 
      - name: Build with Jekyll
        # Outputs to the './_site' directory
        run: |
          ./build.sh
        env:
          CONTAINER_ENGINE: docker
          BUILD_IMAGE_SPEC: localhost:5000/kroxy-jekyll:latest

      # Currently the image shas are not available when we create the release, they need to be manually
      # updated in the release PR before merge.
      - name: Require release manifests to contain non-placeholder container image SHAs
        run: |
          PLACEHOLDER="REPLACE_WITH_SHA_AFTER_IMAGE_RELEASE"
          # || true prevents the script failing when 0 matches are found
          matching_files=$(grep -F -r -l "${PLACEHOLDER}" _data/release/ || true)
          if [[ -n "${matching_files}" ]]; then
            echo "Error: ${PLACEHOLDER} found in release manifests:" >&2
            echo "${matching_files}" >&2
            echo "Please replace the placeholders in these files with the released image SHAs" >&2
            exit 1
          else
            echo "Success: Release manifests contain no image SHA placeholders"
          fi
